pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/<rahul9787>/carwebsite.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo "Build Successful"'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                sudo cp -r * /var/www/html/
                '''
            }
        }
    }
}
